//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiCore.Lib.NDT.CoordinateProvider.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiCore.Lib.NDT.CoordinateProvider.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл № .
        /// </summary>
        internal static string BaseDiagDataProvider_BuildDistanceRangeInformation_1 {
            get {
                return ResourceManager.GetString("BaseDiagDataProvider_BuildDistanceRangeInformation_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  диапазон: .
        /// </summary>
        internal static string BaseDiagDataProvider_BuildDistanceRangeInformation_2 {
            get {
                return ResourceManager.GetString("BaseDiagDataProvider_BuildDistanceRangeInformation_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректно задан датчик ВМТ [{0}]. {1}. {2}.
        /// </summary>
        internal static string BaseDiagDataProvider_FillCarrierRotationMap {
            get {
                return ResourceManager.GetString("BaseDiagDataProvider_FillCarrierRotationMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполняется построение отчета превышения скорости снаряда. Диапазон {0} - {1} м/с. Пожалуйста, подождите ....
        /// </summary>
        internal static string BuildReport {
            get {
                return ResourceManager.GetString("BuildReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка создания idt, неверное показание одометра, номер записи:.
        /// </summary>
        internal static string CDP_ERROR_IDT_CREATING_INVALID_ODOMETER {
            get {
                return ResourceManager.GetString("CDP_ERROR_IDT_CREATING_INVALID_ODOMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  за пределами массива: .
        /// </summary>
        internal static string CDP_ERROR_NOT_IN_ARRAY {
            get {
                return ResourceManager.GetString("CDP_ERROR_NOT_IN_ARRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error open CoordinateDataProvider. Files path: {0}.
        /// </summary>
        internal static string CDP_ERROR_OPEN_CCD {
            get {
                return ResourceManager.GetString("CDP_ERROR_OPEN_CCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нарушено последовательное возрастание показаний одометра!
        ///Попытаться найти последовательным перебором (возможно зависание машины)?.
        /// </summary>
        internal static string CDP_ERROR_SEQ_ODOMETER_SLOW_WORK {
            get {
                return ResourceManager.GetString("CDP_ERROR_SEQ_ODOMETER_SLOW_WORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтрация показаний датчика углового положения. Пожалуйста, подождите....
        /// </summary>
        internal static string CoordinateDataProvider_CCD_Filtration {
            get {
                return ResourceManager.GetString("CoordinateDataProvider_CCD_Filtration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Индекс датчика на кольце вышел за пределы диапазона. Датчик {0}, индекс на кольце {1}.
        /// </summary>
        internal static string DPH_SENSOR_INDEX_NOT_IN_INTERVAL {
            get {
                return ResourceManager.GetString("DPH_SENSOR_INDEX_NOT_IN_INTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размеры векторов не равны.
        /// </summary>
        internal static string DPH_VECTORS_SIZE_DONT_EQ {
            get {
                return ResourceManager.GetString("DPH_VECTORS_SIZE_DONT_EQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл {0} уже существует, для создания нового выполните его удаление!.
        /// </summary>
        internal static string IDT_FILE_EXIST_DELETE_BEFORE {
            get {
                return ResourceManager.GetString("IDT_FILE_EXIST_DELETE_BEFORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл idt отобразился в память не полностью.
        /// </summary>
        internal static string IDT_FILE_IDT_DONT_MAPPING_FULL {
            get {
                return ResourceManager.GetString("IDT_FILE_IDT_DONT_MAPPING_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File pointers {0} have badformat.
        /// </summary>
        internal static string PF_BAD_FORMAT {
            get {
                return ResourceManager.GetString("PF_BAD_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл указателей имеет слишком большой размер и не может быть полностью загружен. {0}.
        /// </summary>
        internal static string PointerFile_BuildPointers_FileBigSizeError {
            get {
                return ResourceManager.GetString("PointerFile_BuildPointers_FileBigSizeError", resourceCulture);
            }
        }
    }
}
